# Generated by Django 4.2.14 on 2024-09-23 14:30

import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'left'], force_format=None, keep_meta=True, quality=80, scale=1, size=[300, 300], upload_to=users.models.file_upload),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name_ru',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name_uz',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=django.contrib.postgres.indexes.HashIndex(fields=['first_name'], name='customuser_first_name_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=django.contrib.postgres.indexes.HashIndex(fields=['last_name'], name='customuser_last_name_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=django.contrib.postgres.indexes.HashIndex(fields=['middle_name'], name='customuser_middle_name_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='customuser_username_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(('birth_year__gt', 1900), ('birth_year__lt', 2024)), name='check_birth_year_range'),
        ),
    ]
