# Generated by Django 4.2.14 on 2024-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_topic_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='users.topic'),
        ),
    ]
