# Generated by Django 4.2.14 on 2024-09-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_article_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(related_name='articles', to='users.topic'),
        ),
    ]
